[package]
name = "gdiroh"
version = "0.1.0"
edition = "2024"

[lib]
# this tells rust to compile the crate as a dynamic C library
crate-type = ["cdylib"]

[dependencies]
godot = "0.4.2"

[workspace]
resolver = "3"
members = ["xtask"]
