edition = "2024"
unstable_features = true

max_width = 100
newline_style = "Unix"

imports_granularity = "Crate"
group_imports = "StdExternalCrate"
imports_layout = "Vertical"

format_code_in_doc_comments = true
format_strings = true
